version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "TrendMicroApp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ty1j4bag6l4p"
s3_prefix = "TrendMicroApp"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"

