version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "newtrend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1a3wuuci6swzy"
s3_prefix = "newtrend"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"

