version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "TrendMicroApp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-5qe7v4fg6748"
s3_prefix = "TrendMicroApp"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"

