AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Sample SAM Template for trend-micro-test-sam

Globals:
  Function:
    Timeout: 3

Resources:
  TrendMicroAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: MyLambdaTokenAuthorizer
        Authorizers:
          MyLambdaTokenAuthorizer:
            FunctionArn: !GetAtt AuthFunction.Arn

  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Authorizer/
      Handler: index.handler
      Runtime: nodejs12.x

  TrendMicroTestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: SecurityGroups/
      Handler: index.handler
      Runtime: nodejs12.x
      Events:
        TrendMicroTest:
          Type: Api
          Properties:
            RestApiId: !Ref TrendMicroAPI
            Path: /GetSecurityGroups
            Method: get

      Policies:
        # Give EC2ReadOnlyAccess to Lambda Function
        - AmazonEC2ReadOnlyAccess

Outputs:
  TrendMicroTestApi:
    Description: "API Gateway endpoint URL for Prod stage for Trend Micro Test function"
    Value: !Sub "https://${TrendMicroAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/GetSecurityGroups/"
  TrendMicroTestFunction:
    Description: "Trend Micro Test Lambda Function ARN"
    Value: !GetAtt TrendMicroTestFunction.Arn
  TrendMicroTestFunctionIamRole:
    Description: "Implicit IAM Role created for Trend Micro Test function"
    Value: !GetAtt TrendMicroTestFunctionRole.Arn
