AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  trend-micro-test-sam

  Sample SAM Template for trend-micro-test-sam
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  TrendMicroTestFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: TrendTestApp/
      Handler: app.Handler
      Runtime: nodejs12.x
      Events:
        TrendMicroTest:
          Type: Api 
          Properties:
            Path: /GetSecurityGroups
            Method: get
      Policies:
      # Give DynamoDB Full Access to your Lambda Function
      - AmazonEC2ReadOnlyAccess

Outputs:

  TrendMicroTestApi:
    Description: "API Gateway endpoint URL for Prod stage for Trend Micro Test function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/GetSecurityGroups/"
  TrendMicroTestFunction:
    Description: "Trend Micro Test Lambda Function ARN"
    Value: !GetAtt TrendMicroTestFunction.Arn
  TrendMicroTestFunctionIamRole:
    Description: "Implicit IAM Role created for Trend Micro Test function"
    Value: !GetAtt TrendMicroTestFunctionRole.Arn
